### ISSUE TITLE
EmailOTP not working when having multiple authenticator options in MFA

### ISSUE THREAD

**Issue by pranavan15** [wso2-extensions/identity-outbound-auth-email-otp#21]
**Description:**
When configuring both SMSOTP and EmailOTP as authenticator options in MFA (EmailOTP is the second option) and trying EmailOTP option, Email goes as expected and UI appears to enter the code. But after entering the code and submitting the below error occurs.

```
org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: Error while sending the HTTP request. 
	at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.proceedWithOTP(SMSOTPAuthenticator.java:475)
	at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.initiateAuthenticationRequest(SMSOTPAuthenticator.java:155)
	at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.process(SMSOTPAuthenticator.java:98)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:467)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handleResponse(DefaultStepHandler.java:441)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:145)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:188)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:130)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:142)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53).
.
#trimed content
.
Caused by: java.net.MalformedURLException: no protocol: 
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.sendRESTCall(SMSOTPAuthenticator.java:884)
	at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.proceedWithOTP(SMSOTPAuthenticator.java:452)
	... 57 more
```

**Suggested Labels:**
Bug

**Affected Product Version:**
Connector versions post 2.0.5

**Steps to reproduce:**
Configure both SMSOTP and EmailOTP as authenticator options in MFA with EmailOTP being the second option and trying using EmailOTP option.

**Comment by pranavan15** [comment]
This issue has been fixed in this [PR](https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/22)
